#!/bin/bash

BRIGHT='/sys/class/backlight/intel_backlight/brightness'
MAX_BRIGHT='/sys/class/backlight/intel_backlight/max_brightness'
VALUE=$1


if ! test $1 ;then 
  exit 1
fi 


CURRENT=$(cat $BRIGHT)
MAX=$(cat $MAX_BRIGHT)

case $1 in 
"up")
  if (($CURRENT + 300 > $MAX))
  then
	  echo $MAX > $BRIGHT
  else
	  echo $CURRENT + 300 | bc > $BRIGHT  
  fi
;;
"down")
  if (($CURRENT - 300 <= 0))
  then
	  echo 0 > $BRIGHT
  else
	  echo $CURRENT - 300 | bc > $BRIGHT  
  fi
esac


CURRENT=$(cat $BRIGHT)
echo $CURRENT
DISPLAY=0:0
CURRENT_PERC=$(bc -l <<< "$CURRENT/$MAX*100")
CURRENT_PERC=$(echo $CURRENT_PERC | sed 's:\..*$::')
notify-send "Brightness level - $CURRENT_PERC%"
